name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute lowercase repo and tags
        id: names
        run: |
          lc_repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "lc_repo=$lc_repo" >> $GITHUB_OUTPUT
          echo "tag_latest=ghcr.io/${lc_repo}:latest" >> $GITHUB_OUTPUT
          echo "tag_sha=ghcr.io/${lc_repo}:sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.names.outputs.tag_latest }}
            ${{ steps.names.outputs.tag_sha }}

      - name: Show where the image was pushed
        run: |
          echo "Pushed:"
          echo "${{ steps.names.outputs.tag_latest }}"
          echo "${{ steps.names.outputs.tag_sha }}"